# Phase Space Files

/control/execute mac/verbose.mac
/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db
/gate/geometry/setIonisationPotential Water 78 eV
/gate/geometry/setIonisationPotential PLA100 77.958580668515992 eV

# WORLD
/gate/world/setMaterial Air
/gate/world/geometry/setXLength 5.0 m
/gate/world/geometry/setYLength 5.0 m
/gate/world/geometry/setZLength 5.0 m

# WATER BOX
/gate/world/daughters/name water_box
/gate/world/daughters/insert box
/gate/water_box/setMaterial Water
/gate/water_box/geometry/setXLength 5 cm
/gate/water_box/geometry/setYLength 10 cm
/gate/water_box/geometry/setZLength 10 cm
/gate/water_box/placement/setTranslation 2.5 0 0 cm
/gate/water_box/vis/setColor blue

# PLAN
/gate/world/daughters/name plane
/gate/world/daughters/insert box
/gate/plane/setMaterial Air
/gate/plane/geometry/setXLength 1 nm
/gate/plane/geometry/setYLength 1 m
/gate/plane/geometry/setZLength 1 m
/gate/plane/placement/setTranslation 5.5 0 0 cm
/gate/plane/vis/setColor magenta

#=====================================================
# PHYSICS 
#=====================================================

/gate/physics/addPhysicsList QGSP_BIC_EMZ
/gate/physics/Gamma/SetCutInRegion world 1 mm
/gate/physics/Electron/SetCutInRegion world 1 mm
/gate/physics/Positron/SetCutInRegion world 1 mm
/gate/physics/Gamma/SetCutInRegion water_box 0.01 mm
/gate/physics/Electron/SetCutInRegion water_box 0.01 mm
/gate/physics/Positron/SetCutInRegion water_box 0.01 mm
/gate/physics/Gamma/SetCutInRegion plane 0.01 mm
/gate/physics/Electron/SetCutInRegion plane 0.01 mm
/gate/physics/Positron/SetCutInRegion plane 0.01 mm

/gate/physics/displayCuts

#=====================================================
# Statistics actor 
#=====================================================

/gate/actor/addActor SimulationStatisticActor stat
/gate/actor/stat/saveEveryNSeconds 120
/gate/actor/stat/save output/stats_PhSp_part1.txt

#=====================================================
# EmCalculator actor 
#=====================================================

/gate/actor/addActor EmCalculatorActor EM-properties
/gate/actor/EM-properties/setParticleName proton
/gate/actor/EM-properties/setEnergy 210 MeV
/gate/actor/EM-properties/save output/EMprops_PhSp_part1.txt

#=====================================================
# Dose actor 
#=====================================================

/gate/actor/addActor DoseActor doseDistribution
/gate/actor/doseDistribution/attachTo water_box
/gate/actor/doseDistribution/stepHitType random
/gate/actor/doseDistribution/enableNumberOfHits false
/gate/actor/doseDistribution/setPosition 0 0 0 cm
/gate/actor/doseDistribution/setResolution 1 1 4000
/gate/actor/doseDistribution/enableDose false
/gate/actor/doseDistribution/enableUncertaintyDose false
/gate/actor/doseDistribution/enableEdep true
/gate/actor/doseDistribution/enableSquaredDose false
/gate/actor/doseDistribution/enableDoseToWater false
/gate/actor/doseDistribution/enableUncertaintyDoseToWater false
/gate/actor/doseDistribution/saveEveryNSeconds 120
/gate/actor/doseDistribution/save output/PhSp_part1.txt

#=====================================================
# Phase Space actor
#=====================================================

/gate/actor/addActor PhaseSpaceActor PhSp
/gate/actor/PhSp/attachTo plane
/gate/actor/PhSp/save output/MyOutputFile.root

/gate/actor/PhSp/enableParticleName true
/gate/actor/PhSp/enableProductionVolume true
/gate/actor/PhSp/enableProductionProcess true
/gate/actor/PhSp/useVolumeFrame true
/gate/actor/PhSp/enableEkine true
/gate/actor/PhSp/enableXPosition true
/gate/actor/PhSp/enableYPosition true
/gate/actor/PhSp/enableZPosition true
/gate/actor/PhSp/enableXDirection true
/gate/actor/PhSp/enableYDirection true
/gate/actor/PhSp/enableZDirection true
/gate/actor/PhSp/enableWeight true
/gate/actor/PhSp/storeOutgoingParticles false
/gate/actor/PhSp/storeSecondaries true

#=====================================================
# INITIALISATION 
#=====================================================

/gate/run/initialize

#=====================================================
# SOURCE 
#=====================================================

/gate/source/addSource PBS TPSPencilBeam
/gate/source/PBS/setTestFlag false
/gate/source/PBS/setPlan data/plan_singlePB.txt
/gate/source/PBS/setFlatGenerationFlag false
/gate/source/PBS/setSpotIntensityAsNbIons false
/gate/source/PBS/setSortedSpotGenerationFlag false
/gate/source/PBS/setSigmaEnergyInMeVFlag false
/gate/source/PBS/setSourceDescriptionFile data/uclhospital_bmv3.txt

#=====================================================
# START BEAMS 
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/application/setTotalNumberOfPrimaries 100000
/gate/application/start
